framework: jest
postMerge:
  pattern: 
    - "./test/react/*-test.js"
preMerge:
  pattern:
    - "./test/react/*-test.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
nodeVersion: 9
version: 1.0 
